### ISSUE TITLE
console

### ISSUE THREAD

**Issue by QGB** [QGB/PythonAnywhere#3]
ssh -o HostKeyAlgorithms=+ssh-rsa -o PubkeyAcceptedKeyTypes=+ssh-rsa -p 2222 127.0.0.1 
```
13:28 ~ $ ./busybox ifconfig
docker0   Link encap:Ethernet  HWaddr 02:42:78:BB:1C:F9  
          inet addr:172.17.0.1  Bcast:172.17.255.255  Mask:255.255.0.0
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

ens5      Link encap:Ethernet  HWaddr 0A:32:2E:79:73:4D  
          inet addr:10.0.0.232  Bcast:10.0.0.255  Mask:255.255.255.0
          inet6 addr: fe80::832:2eff:fe79:734d/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:9001  Metric:1
          RX packets:101478377 errors:0 dropped:0 overruns:0 frame:0
          TX packets:111561441 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:72113893635 (67.1 GiB)  TX bytes:46604117870 (43.4 GiB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:3280478 errors:0 dropped:0 overruns:0 frame:0
          TX packets:3280478 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:874109376 (833.6 MiB)  TX bytes:874109376 (833.6 MiB)

 
```

**Comment by QGB** [comment]
```
Traceback (most recent call last):
  File "/home/anywhere/djangoproject/jails/pa_sudo.py", line 189, in <module>
    main(sys.argv[1:])
  File "/home/anywhere/djangoproject/jails/pa_sudo.py", line 185, in main
    pa_sudo(username, command)
  File "/home/anywhere/djangoproject/jails/pa_sudo.py", line 150, in pa_sudo
    ensure_chroot(username, system_image)
  File "/home/anywhere/djangoproject/jails/pa_sudo.py", line 42, in ensure_chroot
    setup_user_storage(user)
  File "/home/anywhere/djangoproject/jails/../jails/create.py", line 505, in setup_user_storage
    create_dirs_on_storage_servers(user)
  File "/home/anywhere/djangoproject/jails/../jails/create.py", line 207, in create_dirs_on_storage_servers
    mkdir_if_missing(home)
  File "/home/anywhere/djangoproject/jails/../../common/directory.py", line 50, in mkdir_if_missing
    os.makedirs(dirname)
  File "/usr/lib/python3.7/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.7/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.7/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.7/os.py", line 223, in makedirs
    mkdir(name, mode)
OSError: [Errno 116] Stale file handle: '/mnt/fileserver3/homedirs'
Console closed.
```

文件系统错误
